### ISSUE TITLE
Regexp can be even better

### ISSUE THREAD

**Issue by groundf** [czech-radio/openmedia-check#6]
https://github.com/czech-radio/openmedia-check/blob/77a5aa9fb55e984a212f01a4861ae4c5ab2adf2d/check.go#L53

`([12]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]))`
https://www.regextester.com/96683

Works for dates `1000-01-01` > `$date` <  `2999-12-31`

**Comment by K0F** [comment]
nejak to tam nefacha
reg := regexp.MustCompile("[12]\\d{3}(0[1-9]|1[0-2])(0[1-9]|[12]\\d|3[01])")

**Comment by groundf** [comment]
It works on regextester, I will try Go later. At this moment keep what already works.
